# Coordinates of the fractal
Real: -0.757 # Defaults to -1
Imaginary: 0.068 # Defaults to -1

# Size (pixels)
Width: 1024 # Defaults to 1024
Height: 1024 # Defaults to 1024

# Colour - Lower is lighter
# The value is used in the equation x / (x + falloff)
RFalloff: 15 # Defaults to 15
GFalloff: 100 # Defaults to 100
BFalloff: 500 # Defaults to 500

# Brightness assigned to points that don't escape to infinity
# Higher is lighter
# Set to MaxIterations (normally 1000) to prevent fireflies
# Defaults to 0
NonEscapingValue: 1000

# The number of times the Julia equation is run to determine if a point will escape
# Defaults to 1000
MaxIterations: 1000

# Escape radius - The distance from its start at which a point is considered "escaped"
# Defaults to 4
Radius: 4

# Border values - The values at the edges of the screen (used to change zoom, aspect ratio)
# Max values must be greater than min values
# Defaults to -2, 2 for both x and y
MinX: -2
MaxX: 2
MinY: -2
MaxY: 2

# Output Path
# Defaults to the CWD
# OutputPath: ../../ # This will put the output files 2 directories up
