# All of these parameters are optional, comment them out or remove them to let the default values get used

### Fractal Parameters ###
# Fractal type
# Julia - generates julia set using Real and Imaginary values
# MultiJulia - generates multi julia / mandelbrot set using MultiJuliaExponent value
# Defaults to Julia
FractalType: Julia

# Coordinates of the fractal (julia set only)
# Both default to 0
Real: 0
Imaginary: 0

# Exponent of multi julia set (multi julia set only)
# Defaults to 2
MultiJuliaExponent: 2

### Image Parameters ###
# Image size (pixels)
# Both default to 1024
Width: 1024
Height: 1024

# The strength of the colour falloff, used in the equation: colourStrength = fractalValue / (fractalValue + strength)
# Also written as: y = x / (x + s)
# Higher is less colour but more detailed, lower is more colour but less detailed and more blown out
# Defaults to 15
FalloffStrength: 15

# The RGB colour values of the falloff, ranging between 0 and 1
# All default to 1
FalloffR: 1
FalloffG: 1
FalloffB: 1

# The RGB colour values of the background, ranging between 0 and 1
# The background can also be transparent
# All default to 0 except for alpha, which defaults to 1
BackgroundR: 0
BackgroundG: 0
BackgroundB: 0
BackgroundA: 1

# Output path of the fractal image
# Defaults to the CWD
# OutputPath: ../../ #  As an example, this would put the output files 2 directories up

### Transformation Parameters ###
# Whether a non-square image will adjust the fractal to avoid skewing
# Defaults to true
AdjustForAspectRatio: true

# Offset of the fractal from the centre of the image
# Increasing X moves the fractal to the right
# Increasing Y moves the fractal down
# Both default to 0
OffsetX: 0
OffsetY: 0

# Controls the scale of the fractal on both the X and Y axes
# Both default to 1
ScaleX: 1
ScaleY: 1

### Calculation Parameters ###
# Brightness assigned to points that don't escape to infinity
# Higher is lighter (max 1), lower is darker (min 0), and can be used to prevent fireflies
# Recommended to set to 1 for julia fractal, and 0 for multi julia
# Defaults to 0
NonEscapingValue: 0

# The number of times the fractal equation is run to determine if a point will escape
# Recommended to lower if you have a low-end computer or are generating a multi julia, as it is very computationally expensive
# Defaults to 1000
MaxIterations: 1000

# The distance from a pixels starting position at which it is considered "escaped"
# Defaults to 4
EscapeRadius: 4
